server:
  port: 3002
  
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    
 